### ISSUE TITLE
class file not recognized by jmeter

### ISSUE THREAD

**Issue by smokyFox8** [avisi/jmeter-mllp-tcpclient#2]
Hi 

First of all thank you for developing and sharing this. 

Jmeter does not use class: nl.avisi.jmeter.mllpsampler.MllpTCPClient.

I have but the jar file mllptcpsampler-1.0-SNAPSHOT.jar in

C:\apache-jmeter-2.11\lib\ext

and also tried the following path but none of them worked:
C:\apache-jmeter-2.11\lib

any suggestion 

![mllp](https://cloud.githubusercontent.com/assets/13210893/13835788/6e17410c-ec4f-11e5-9588-8c711b52465a.PNG)

**Comment by smokyFox8** [comment]
I have attached the jar file i used in jmeter

[mllptcpsampler-1.0-SNAPSHOT.zip](https://github.com/avisi/jmeter-mllp-tcpclient/files/177260/mllptcpsampler-1.0-SNAPSHOT.zip)

**Comment by milters** [comment]
Thank you for sharing. I'm experiencing the same problem. Did you find a solution? If so, please share.

**Comment by smokyFox8** [comment]
i have not found anything yet. My team and I have moved on with C#. Please
let me know how you go.

**Comment by maidiepe** [comment]
Hi Guys, i've tried it with 2.11 and 3.0 and it still works, see the attached screenshots.

I've put the jar in lib/ext and pointed to the nl.avisi.jmeter.mllpsampler.MllpTCPClient class within jmeter. 

Could you share some logging or settings with me so that we can hopefully fix the issue ?
<img width="563" alt="screenshot 2016-07-14 06 46 35" src="https://cloud.githubusercontent.com/assets/16643099/16828321/fd8fdece-498e-11e6-9d63-5e08c509f8b8.png">

<img width="720" alt="screenshot_client" src="https://cloud.githubusercontent.com/assets/16643099/16828334/1c26fd0e-498f-11e6-93f9-b5e4f68b0085.png">

**Comment by rkettelerij** [comment]
Thanks @maidiepe for taking a look. I've just checked it with JMeter 2.13 and it works just fine. First copy the jar to <jmeter>/lib/ext. Then start JMeter, point class to avisi.jmeter.mllpsampler.MllpTCPClient and fire away. See the screenshot below. 
<img width="1016" alt="screen shot 2016-07-15 at 22 13 10" src="https://cloud.githubusercontent.com/assets/291572/16887334/b7b97882-4ad9-11e6-8bce-bb08d9d9cd3d.png">
Log files and screenshots would be helpful in order to reproduce this issue.

**Comment by smokyFox8** [comment]
works for me also. thanks for the support @rkettelerij and @maidiepe
